In [1]:
# import linear_interp
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000)
import linear_interp

In [2]:
np.random.seed(1234)

data = np.random.random((1,1)) * 9
dims = np.array([np.arange(10)], dtype=np.float64)

foo = linear_interp.py_bin_with_interpolation(data, dims)
foo

[[1.9151945]]


array([0.       , 0.0848055, 0.9151945, 0.       , 0.       , 0.       , 0.       , 0.       , 0.       , 0.       ])

Point: (1.915195, 0.000000) 
-0.084805
next
k: 0
Debug temp_arr1 print loop
0 
Debug temp_arr2 print loop
0 
Debug temp_arr1 print loop
2 
lin 2
dir 1
lin bin before 1.000000
dir bin before 0.000000
lin bin after  0.915195
dir bin after  0.084805
Debug prev directions print loop
-1 


In [3]:
np.random.seed(1234)

# data = np.random.random((2, 1)) * 9
# data = np.array([[1.8], [1.8]], dtype=np.float64)  # Good
# data = np.array([[1.35], [1.8]], dtype=np.float64)  # Reversed dimensions?
data = np.array([[1.35], [1.35]], dtype=np.float64)  # Fails on all equal

dim_0 = np.arange(10)
dim_1 = np.arange(10)
dims = np.array([dim_0, dim_1], dtype=np.float64)

print(dims)
print(data)

foo = linear_interp.py_bin_with_interpolation(data, dims)
foo


# linear_interp.py_bin_with_interpolation(data, dims)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[1.35]
 [1.35]]
[[1.5 1.5]]


array([[0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.25, 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

Point: (1.500000, 1.500000) 
-0.500000
next
k: 0
Debug temp_arr1 print loop
0 0 
Debug temp_arr2 print loop
0 0 
Debug temp_arr1 print loop
2 2 
lin 22
dir 12
lin bin before 1.000000
dir bin before 0.000000
lin bin after  0.500000
dir bin after  0.500000
Debug prev directions print loop
-1 0 
-0.500000
next
k: 0
Debug temp_arr1 print loop
0 0 
Debug temp_arr2 print loop
0 0 
Debug temp_arr1 print loop
2 2 
lin 22
dir 21
lin bin before 0.500000
dir bin before 0.000000
lin bin after  0.250000
dir bin after  0.250000
k: 1
Debug temp_arr1 print loop
1 0 
Debug temp_arr2 print loop
-1 0 
Debug temp_arr1 print loop
1 2 
lin 12
dir 11
lin bin before 0.500000
dir bin before 0.000000
lin bin after  0.250000
dir bin after  0.250000
Debug prev directions print loop
-1 -1 


In [4]:
linear_interp.py_vector_mult_int(
    [0, 1],
    [-1, 0]
)

array([0, 0], dtype=int32)

In [5]:
np.set_printoptions(edgeitems=30, linewidth=100000)
foo

array([[0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.0848055 , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.55525249, 0.15760376, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.        , 0.   

In [3]:
a = [3, 2, 1]
b = [7, 8, 9]

a_int = np.array([3, 2, 1], dtype=int)
b_int = np.array([7, 8, 9], dtype=int)

a_double = np.array([3, 2, 1], dtype=np.float64)
b_double = np.array([7, 8, 9], dtype=np.float64)

In [4]:
linear_interp.py_vector_min_int(a)
linear_interp.py_vector_min_int(b)

7

In [5]:
# linear_interp.py_dot_product_int(a, b)
# linear_interp.py_vector_add_int(a, b)
linear_interp.py_vector_mult_int(a, b)

array([21, 16,  9], dtype=int32)

In [6]:
# linear_interp.py_dot_product_double(a, b)
# linear_interp.py_vector_add_double(a, b)
linear_interp.py_vector_mult_double(a, b)

array([21., 16.,  9.])