In [1]:
# import linear_interp
import numpy as np
import linear_interp

In [2]:
import numpy as np
import linear_interp
np.random.seed(1234)

data = np.random.random((2, 4)) * 9

dim_0 = np.arange(10)
dim_1 = np.arange(10)
dims = np.array([dim_0, dim_1], dtype=np.float64)

print(dims)
print(data)

linear_interp.py_bin_with_interpolation(data, dims)



# linear_interp.py_bin_with_interpolation(data, dims)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[1.72367505 5.59897894 3.93954965 7.06822725]
 [7.01978227 2.45333345 2.4881783  7.2168496 ]]
[[1.9151945  7.79975808]
 [6.22108771 2.72592605]
 [4.37727739 2.76464255]
 [7.85358584 8.01872178]]
Point: (1.915195, 7.799758) 
-0.084805
next
k: 0
0.221088
next
k: 0
k: 1
Point: (6.221088, 2.725926) 
0.377277
next
k: 0
-0.146414
next
k: 0
k: 1
Point: (4.377277, 2.764643) 
-0.200242
next
k: 0
-0.274074
next
k: 0
k: 1
Point: (7.853586, 8.018722) 
-0.235357
next
k: 0
0.018722
next
k: 0
k: 1


array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.67844397, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 5.16212499, 1.20545554, 0.4707149 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 1.72754951, 0.01837127],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.62488528, 4.26576652, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 2.26366434, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.       

In [3]:
a = [3, 2, 1]
b = [7, 8, 9]

a_int = np.array([3, 2, 1], dtype=int)
b_int = np.array([7, 8, 9], dtype=int)

a_double = np.array([3, 2, 1], dtype=np.float64)
b_double = np.array([7, 8, 9], dtype=np.float64)

In [4]:
linear_interp.py_vector_min_int(a)
linear_interp.py_vector_min_int(b)

7

In [5]:
# linear_interp.py_dot_product_int(a, b)
# linear_interp.py_vector_add_int(a, b)
linear_interp.py_vector_mult_int(a, b)

array([21, 16,  9], dtype=int32)

In [6]:
# linear_interp.py_dot_product_double(a, b)
# linear_interp.py_vector_add_double(a, b)
linear_interp.py_vector_mult_double(a, b)

array([21., 16.,  9.])